name: build and deploy GitHub Pages

on: 
 push:
  branches:
   - master

jobs:
  build:
    name: publish website
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0

        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
